[Variables]
Element=30
Corner=6
Padding=8
TopBarWidth=#Element#
SideBarWidth=(#Element#+2*#Padding#)

; Background
Colour.Background=245,245,245
Colour.Background.Alpha=255
; Foreground
Colour.Foreground=238,238,238
Colour.Foreground.Alpha=255
; SideBar
Colour.SideBar=195,195,255
Colour.SideBar.Alpha=255
; TopBar
Colour.TopBar=140,140,255
Colour.TopBar.Alpha=255
; Element
Colour.Element=65,65,65
Colour.Element.Alpha=255
; Highlight
Colour.Highlight=110,110,110
Colour.Highlight.Alpha=255

; -------------------------------------

; Adjustable but not recommended
Font.Display=Inconsolata
Font.DisplayS=(#Element#*1/3)

; Do not adjust
Font.Icon=MaterialIcon
Font.IconS=(#Element#*0.75)
