[Variables]
ElementSize=40
Padding=10
CornerRadius=6

IntAreaWidth=250
MEWidth=(#IntAreaWidth#-2*#Padding#)
MEHeight=#ElementSize#
ShownModules=6
IntAreaHeight=(#Padding#+#ShownModules#*(#MEHeight#+#Padding#))

LineWidth=4
IntAreaHeaderWidth=80
IntAreaButtonWidth=160

Skin.Width=(2*#IntAreaWidth#+4*#LineWidth#+9*#Padding#)
Skin.Height=700

IntScrollSpeed=5

Colour.1=225,63,63
Colour.2=255,255,255