[Variables]
body.ElementSize=30
body.Padding=8
body.CornerRadius=6

; Background
colour.1.Code=25,25,25
colour.1.Alpha=255
; Element
colour.2.Code=200,200,200
colour.2.Alpha=255
; Highlight
colour.3.Code=220,220,220
colour.3.Alpha=20

font.DisplayName=Inconsolata	
font.IconName=MaterialIcon
font.SizeStd=(#body.ElementSize#*1/3)

body.PopUpGap=5
body.X=((#ScreenAreaWidth#-#body.Width#)/2)
body.Y=1034
body.Width=1500
body.Height=(#body.ElementSize#+#body.Padding#*2)
